DEBUG = False

RAISE_IN_TRANSFORMER = True

BROKER_URL = 'amqp://guest@localhost'

CELERY_EAGER_PROPAGATES_EXCEPTIONS = True

RECORD_HTTP_TRANSACTIONS = False

RAW_PROCESSING = []
NORMALIZED_PROCESSING = []

SENTRY_DSN = None

USE_FLUENTD = False
FLUENTD_ARGS = {
    'tag': 'app.scrapi'
}
